### ISSUE TITLE
Error in holder and base velocity blocks

### ISSUE THREAD

**Issue by azadm** [robotology-playground/WBI-Toolbox#63] opened 2015-01-23 15:48 UTC
This is the error that I get when I add either a `holder` or a `baseVelocity` block in my simulink file:

```
Error using sf
object[id]!=NULL
```

I am using Matlab R2013a.

**Comment by francesco-romano** [comment] 2015-01-29 14:17
I'm closing this issue because is a duplicate of  https://github.com/robotology-playground/WBI-Toolbox/issues/69 and on the other issue there is more information.

@azadm please look at #69

**Closed by francesco-romano** 2015-01-29 14:17 UTC
