### ISSUE TITLE
After using torque control the robot remains in torque control mode

### ISSUE THREAD

**Issue by robertocalandra** [robotology-playground/WBI-Toolbox#53] opened 2015-01-15 17:53 UTC
After using the torque control, the joint are unresponsive (also to restarting the robotInterface).
It took me a while to notice from the robotMotorGui that the joints were in hardware fault...
Would it make sense to automatically switch back to position control at the end of the execution?

**Comment by jeljaik** [comment] 2015-01-15 18:44
The normal behavior of the WBI-Toolbox is exactly that of leaving the robot
in the position control mode. I think you will need to provide further
information to understand if this is caused by our code or not. Nonetheless
we'll check tomorrow. Is it replicable by just trying to set torques with
the corresponding block?

**Comment by randaz81** [comment] 2015-01-15 20:22
No, I think that the wholeBodyDynamics(Tree) module, which is responsible
for joint torque estimations, was terminated (or crashed, or disconnected
from the network for more than 100milliseconds) BEFORE closing the toolbox.
As indicated in the control mode specifications, all these conditions
trigger an hardware fault (in order to protect joints from a sudden jerky
movement), which can be cleared only from the robotMotorGui or turning off
the control boards: as you reported, restarting robotInterface is not
sufficient.

2015-01-15 19:44 GMT+01:00 Jorhabib Eljaik <notifications@github.com>:

**Comment by traversaro** [comment] 2015-01-15 22:42
For more information on the iCub control modes, please check: http://wiki.icub.org/wiki/Control_Modes

**Comment by serena-ivaldi** [comment] 2015-01-18 18:41
just to be sure, whenever we use WBI we have to use it with wholeBodyDynamicsTree?

**Comment by DanielePucci** [comment] 2015-01-18 18:55
The WBIToolbox is, at all intents and purposes, an interface. So, you can use it as you would use the WBI. Then,  wholeBodyDynamicsTree must be up only if  modules requiring the information from it are running.

**Comment by traversaro** [comment] 2015-01-19 07:54
In a nutshell: if you need to measure/control torques (readTorques,setTorques) the wholeBodyDynamics/wholeBodyDynamicsTree should be up.

**Closed** 2015-02-19 15:07 UTC
